name: Build and Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  release:
    name: Create Release and Build
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # LTS

      - name: Install dependencies
        run: |
          brew install dpkg gnu-sed
          echo "$(brew --prefix gnu-sed)/libexec/gnubin" >> $GITHUB_PATH
          npm install

      - name: Build all platforms
        run: npm run build:all

      - name: Upload binaries to Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/releases/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
